services:
  app:
    stdin_open: true
    tty: true
    image: container-hzv-qb4
    build:
      context: ./src
    ports:
      - "5000:5000"
      - "20128:20128"
    environment:
      PORT: "20128"
      HOSTNAME: "0.0.0.0"
      HOST: "0.0.0.0"
      NEXT_PUBLIC_BASE_URL: "http://localhost:20128"
